# Multivariate Analysis Using Python about Public Health Data

### Notebook by [Nasr-edine DRAI](https://www.hackerrank.com/d_nasredine)



### [Openclassrooms](https://openclassrooms.com/en/)

## Introduction

In this notebook, I'm going to go over a basic Python data analysis from start to finish to show you how to use python libraries to perform exploratory data analysis and perform multivariate statistical analysis about public health data.

## The problem domain

For the purposes of this project, "The French Public Health Agency (Santé publique France) has launched a call for projects to make public health data more accessible and usable by its agents. As part of this call for projects, the agency wants individuals or teams to carry out an initial exploration and visualization of the data, so that agents can use these results to effectively exploit the data."

<img src="../imgs/french_public_health_agency.png" />

## Verify Python Virtual Environments

#### Check the Version of the Python Interpreter

In [1]:
!python --version

Python 3.10.4


#### Verify that I'm using the right virtual environment

In [2]:
!pip -V

pip 22.3.1 from /Users/drainasr-edine/github/ingenieur_ia/P3_drai_nasr-edine/ia_project_3_env/lib/python3.10/site-packages/pip (python 3.10)


#### Check Installed Modules in Python

Run through this notebook to make sure my environment is properly setup. Be sure to launch Jupyter from inside the virtual environment.

In [3]:
import os, sys

parent = os.path.abspath('..')
sys.path.insert(1, parent)
print(parent)

/Users/drainasr-edine/github/ingenieur_ia/P3_drai_nasr-edine


This code allows me to import modules from the parent directory in my notebook

In [4]:
from srcs.check_environment import run_checks
run_checks()

Using Python in /Users/drainasr-edine/github/ingenieur_ia/P3_drai_nasr-edine/ia_project_3_env:
[ OK ] Python is version 3.10.4 (main, Jul 17 2022, 13:52:49) [Clang 13.1.6 (clang-1316.0.21.2.5)]

[ OK ] jupyterlab
[ OK ] matplotlib
[ OK ] numpy
[ OK ] pandas
[ OK ] seaborn
[ OK ] statsmodels
[ OK ] folium


## Import Python library for data science

In [5]:
# Data manipulation

# Import the pandas library for data manipulation and analysis
import pandas as pd

# Import the numpy library for scientific computing and numerical operations
import numpy as np 

# Import the statsmodels library for statistical analysis and modeling
import statsmodels.api as sm


# Import libraries for data visualization
import matplotlib.pyplot as plt 
import seaborn as sns

# import folium
# from folium.plugins import HeatMap

## Collecting the data

#### Creating a `DataFrame` by Reading in a CSV File

We will read in a CSV file using `pandas`. 

In [6]:
data = pd.read_csv("../data/test.csv", sep="\t")

/var/folders/2y/42rcpdbd4hn6jhp9z8pq2nz40000gn/T/ipykernel_26454/2623078973.py:1: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,35,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/test.csv", sep="\t")


<div class="alert alert-warning">
The warning indicates that a data file or dataset contains columns with mixed data types, which can cause problems when working with the data. The warning suggests specifying the data type for each column or setting the "low_memory" option to "False" to avoid potential problems.
</div>

In [7]:
data = pd.read_csv("../data/test.csv", sep="\t", low_memory=False)

## Quick Examining dataframe

#### Is it empty?

In [8]:
if data.empty:
    print("The DataFrame is empty.")
else:
    print("The DataFrame is not empty.")

The DataFrame is not empty.


#### What are the dimensions?

We find the dimensions with the `shape` attribute as (rows, columns).

In [9]:
data.shape

(320772, 162)

#### What columns do we have?

In [10]:
columns = data.columns
for column in columns:
    print(column)

code
url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_fr
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_fr
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_fr
ingredients_text
allergens
allergens_fr
traces
traces_tags
traces_fr
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_fr
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_fr
main_category
main_category_fr
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
butyr

#### What data types do we have?

We find the data types with the `dtypes` attribute:

In [11]:
# Print the different data types in the DataFrame
print(data.dtypes.unique())

[dtype('O') dtype('float64')]


In [12]:
data.dtypes

code                        object
url                         object
creator                     object
created_t                   object
created_datetime            object
                            ...   
carbon-footprint_100g      float64
nutrition-score-fr_100g    float64
nutrition-score-uk_100g    float64
glycemic-index_100g        float64
water-hardness_100g        float64
Length: 162, dtype: object

#### What does the data look like?

View rows from the top with `head()`:

In [13]:
data.head()

code                                                url  \
0  0000000003087  http://world-fr.openfoodfacts.org/produit/0000...   
1  0000000004530  http://world-fr.openfoodfacts.org/produit/0000...   
2  0000000004559  http://world-fr.openfoodfacts.org/produit/0000...   
3  0000000016087  http://world-fr.openfoodfacts.org/produit/0000...   
4  0000000016094  http://world-fr.openfoodfacts.org/produit/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity  ... ph_100g fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...     NaN                         NaN   
1          NaN      NaN  ...     NaN                         NaN   
2          NaN      NaN  ...     NaN                         NaN   
3          NaN      NaN  ...     NaN                         NaN   
4          NaN      NaN  ...     NaN                         NaN   

  collagen-meat-protein-ratio_100g cocoa_100g chlorophyl_100g  \
0                              NaN        NaN             NaN   
1                              NaN        NaN             NaN   
2                              NaN        NaN             NaN   
3                              NaN        NaN             NaN   
4                              NaN        NaN             NaN   

  carbon-footprint_100g nutrition-score-fr_100g nutrition-score-uk_100g  \
0                   NaN                     NaN                     NaN   
1                   NaN                    14.0                    14.0   
2                   NaN                     0.0                     0.0   
3                   NaN                    12.0                    12.0   
4                   NaN                     NaN                     NaN   

  glycemic-index_100g water-hardness_100g  
0                 NaN                 NaN  
1                 NaN                 NaN  
2                 NaN                 NaN  
3                 NaN                 NaN  
4                 NaN                 NaN  

[5 rows x 162 columns]

## Describing and Summarizing

#### Get summary statistics

Let's start by printing out some summary statistics about the data set.

In [14]:
data.describe()

no_nutriments    additives_n  ingredients_from_palm_oil_n  \
count            0.0  248939.000000                248939.000000   
mean             NaN       1.936024                     0.019659   
std              NaN       2.502019                     0.140524   
min              NaN       0.000000                     0.000000   
25%              NaN       0.000000                     0.000000   
50%              NaN       1.000000                     0.000000   
75%              NaN       3.000000                     0.000000   
max              NaN      31.000000                     2.000000   

       ingredients_from_palm_oil  ingredients_that_may_be_from_palm_oil_n  \
count                        0.0                            248939.000000   
mean                         NaN                                 0.055246   
std                          NaN                                 0.269207   
min                          NaN                                 0.000000   
25%                          NaN                                 0.000000   
50%                          NaN                                 0.000000   
75%                          NaN                                 0.000000   
max                          NaN                                 6.000000   

       ingredients_that_may_be_from_palm_oil  nutrition_grade_uk  \
count                                    0.0                 0.0   
mean                                     NaN                 NaN   
std                                      NaN                 NaN   
min                                      NaN                 NaN   
25%                                      NaN                 NaN   
50%                                      NaN                 NaN   
75%                                      NaN                 NaN   
max                                      NaN                 NaN   

        energy_100g  energy-from-fat_100g       fat_100g  ...    ph_100g  \
count  2.611130e+05            857.000000  243891.000000  ...  49.000000   
mean   1.141915e+03            585.501214      12.730379  ...   6.425698   
std    6.447154e+03            712.809943      17.578747  ...   2.047841   
min    0.000000e+00              0.000000       0.000000  ...   0.000000   
25%    3.770000e+02             49.400000       0.000000  ...   6.300000   
50%    1.100000e+03            300.000000       5.000000  ...   7.200000   
75%    1.674000e+03            898.000000      20.000000  ...   7.400000   
max    3.251373e+06           3830.000000     714.290000  ...   8.400000   

       fruits-vegetables-nuts_100g  collagen-meat-protein-ratio_100g  \
count                  3036.000000                        165.000000   
mean                     31.458587                         15.412121   
std                      31.967918                          3.753028   
min                       0.000000                          8.000000   
25%                       0.000000                         12.000000   
50%                      23.000000                         15.000000   
75%                      51.000000                         15.000000   
max                     100.000000                         25.000000   

       cocoa_100g  chlorophyl_100g  carbon-footprint_100g  \
count  948.000000              0.0             268.000000   
mean    49.547785              NaN             341.700764   
std     18.757932              NaN             425.211439   
min      6.000000              NaN               0.000000   
25%     32.000000              NaN              98.750000   
50%     50.000000              NaN             195.750000   
75%     64.250000              NaN             383.200000   
max    100.000000              NaN            2842.000000   

       nutrition-score-fr_100g  nutrition-score-uk_100g  glycemic-index_100g  \
count            221210.000000            221210.000000                  0.0   
mean                  9.165535             

We can see several useful values from this table. For example, we can see that several columns are empty. 

#### Getting extra info and finding nulls

Let’s print the full summary of the dataframe.

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320772 entries, 0 to 320771
Columns: 162 entries, code to water-hardness_100g
dtypes: float64(106), object(56)
memory usage: 396.5+ MB


In [15]:
unix_time = []
iso8601_time = []
list_of_tags = []
amount_of_a_nutriment_for_100 = []
amount_of_a_nutriment_for_1_serving = []
for column in columns:
    if column.endswith('_t'):
        unix_time.append(column)
    elif column.endswith('_datetime'): 
        iso8601_time.append(column)
    elif column.endswith('_tags'):
        list_of_tags.append(column)
    elif column.endswith('_100g'):
        amount_of_a_nutriment_for_100.append(column)
    elif column.endswith('_serving'):
        amount_of_a_nutriment_for_1_serving.append(column)
time_columns = unix_time + iso8601_time
time_columns

['created_t', 'last_modified_t', 'created_datetime', 'last_modified_datetime']

## Cleaning the data

#### Columns That are empty

In [17]:
# Find the columns where each value is null
empty_cols = [col for col in data.columns if data[col].isnull().all()]
empty_cols

['no_nutriments',
 'ingredients_from_palm_oil',
 'ingredients_that_may_be_from_palm_oil',
 'nutrition_grade_uk',
 'butyric-acid_100g',
 'caproic-acid_100g',
 'lignoceric-acid_100g',
 'cerotic-acid_100g',
 'melissic-acid_100g',
 'elaidic-acid_100g',
 'mead-acid_100g',
 'erucic-acid_100g',
 'nervonic-acid_100g',
 'chlorophyl_100g',
 'glycemic-index_100g',
 'water-hardness_100g']

In [18]:
# Drop these columns from the dataframe
data.drop(empty_cols, axis=1, inplace=True)

In [19]:
data.shape[1]

146

#### Columns That Contain a Single Value

In [20]:
# select columns that have only one unique value
cols = data.loc[:, data.nunique() == 1].columns
for col in cols:
    print(col)

caprylic-acid_100g
myristic-acid_100g
palmitic-acid_100g
stearic-acid_100g
montanic-acid_100g


In [21]:
data['caprylic-acid_100g'].unique()

array([nan, 7.4])

In [22]:
data['myristic-acid_100g'].unique()

array([ nan, 18.9])

In [23]:
data['palmitic-acid_100g'].unique()

array([nan, 8.1])

In [24]:
data['stearic-acid_100g'].unique()

array([nan,  3.])

In [25]:
data = data.drop(labels=cols, axis=1)
data.shape

(320772, 141)

#### Columns That have Very Few Values

In [26]:
# get columns that have only two or fewer unique values
cols = data.loc[:, data.nunique() <= 2].columns
cols

Index(['capric-acid_100g'], dtype='object')

In [27]:
data['capric-acid_100g'].unique()

array([ nan, 5.88, 6.2 ])

In [28]:
data['capric-acid_100g'].var()


0.05120000000000009

In [29]:
# drop columns that have only two or fewer unique values
data = data.drop(labels=cols, axis=1)


#### Rows That Contain Duplicate Data

In [30]:
# drop duplicate rows
data = data.drop_duplicates()

In [31]:
data.shape

(320772, 140)

In [32]:
# get columns that have both numeric and non-numeric data
cols = data.select_dtypes(include=['number', 'object']).columns
for col in cols:
    print(col)

code
url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_fr
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_fr
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_fr
ingredients_text
allergens
allergens_fr
traces
traces_tags
traces_fr
serving_size
additives_n
additives
additives_tags
additives_fr
ingredients_from_palm_oil_n
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_fr
main_category
main_category_fr
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
lauric-acid_100g
arachidic-acid_100g
behenic-acid_100g
monounsaturated-fat_100g
polyunsaturated-fat_10

In [46]:
# Infer the data types of the columns in the DataFrame
data = data.infer_objects()

A value of 'France' does not make sense for the Unix timestamps and indicates an invalid or missing value

In [45]:
data.loc[data.created_t == 'France']

Empty DataFrame
Columns: [code, url, creator, created_t, created_datetime, last_modified_t, last_modified_datetime, product_name, generic_name, quantity, packaging, packaging_tags, brands, brands_tags, categories, categories_tags, categories_fr, origins, origins_tags, manufacturing_places, manufacturing_places_tags, labels, labels_tags, labels_fr, emb_codes, emb_codes_tags, first_packaging_code_geo, cities, cities_tags, purchase_places, stores, countries, countries_tags, countries_fr, ingredients_text, allergens, allergens_fr, traces, traces_tags, traces_fr, serving_size, additives_n, additives, additives_tags, additives_fr, ingredients_from_palm_oil_n, ingredients_from_palm_oil_tags, ingredients_that_may_be_from_palm_oil_n, ingredients_that_may_be_from_palm_oil_tags, nutrition_grade_fr, pnns_groups_1, pnns_groups_2, states, states_tags, states_fr, main_category, main_category_fr, image_url, image_small_url, energy_100g, energy-from-fat_100g, fat_100g, saturated-fat_100g, lauric-acid_100g, arachidic-acid_100g, behenic-acid_100g, monounsaturated-fat_100g, polyunsaturated-fat_100g, omega-3-fat_100g, alpha-linolenic-acid_100g, eicosapentaenoic-acid_100g, docosahexaenoic-acid_100g, omega-6-fat_100g, linoleic-acid_100g, arachidonic-acid_100g, gamma-linolenic-acid_100g, dihomo-gamma-linolenic-acid_100g, omega-9-fat_100g, oleic-acid_100g, gondoic-acid_100g, trans-fat_100g, cholesterol_100g, carbohydrates_100g, sugars_100g, sucrose_100g, glucose_100g, fructose_100g, lactose_100g, maltose_100g, maltodextrins_100g, starch_100g, polyols_100g, fiber_100g, proteins_100g, casein_100g, serum-proteins_100g, nucleotides_100g, salt_100g, sodium_100g, alcohol_100g, ...]
Index: []

[0 rows x 140 columns]

Here we use the `to_datetime` function to convert a column containing Unix timestamps to a datetime data type:


In [43]:
unix_time = []
for column in columns:
    if column.endswith('_t'):
        data[column] = pd.to_datetime(data[column], unit="s", errors='coerce')
        print(data[column].dtypes)

datetime64[ns]
datetime64[ns]


the term `errors='coerce'` is used to indicate that invalid or missing values in a data frame should be converted (or coerced) to a null or missing value.

In [44]:
data.created_t.head()

0   2016-09-17 09:17:46
1   2017-03-09 14:32:37
2   2017-03-09 14:32:37
3   2017-03-09 10:35:31
4   2017-03-09 10:34:13
Name: created_t, dtype: datetime64[ns]